import {
  Box,
  Cloud,
  Code2,
  Database,
  FileCode2,
  GitCompare,
  Rocket,
  ShieldCheck,
} from 'lucide-react';
import type { ComponentType } from 'react';
import type { PageKey } from '../../app/pages';

export interface CapabilityGroup {
  title: string;
  description: string;
  icon: ComponentType<{ className?: string }>;
  route: PageKey;
  routeLabel: string;
  items: [name: string, detail: string][];
}

/** Every row maps to a current frontend workflow and, where needed, a fixed backend operation. */
export const CAPABILITY_GROUPS: CapabilityGroup[] = [
  {
    title: 'Organizations & access',
    description: 'Salesforce CLI authorization and org context without exposing credentials.',
    icon: Cloud,
    route: 'org',
    routeLabel: 'Open org information',
    items: [
      ['Authorized org selector', 'List locally authorized orgs and switch the active application context.'],
      ['Browser authorization', 'Authorize Production, Developer, Sandbox, or Dev Hub environments through sf org login web.'],
      ['Authorization preferences', 'Set an alias, preferred browser, default org, and Dev Hub during authorization.'],
      ['Safe org information', 'Review username, org ID, instance URL, connection state, and environment without verbose secrets.'],
      ['Open Salesforce', 'Launch the selected org directly in the browser through the CLI.'],
      ['Org limits', 'Inspect current API and platform capacity with used and remaining values.'],
      ['Installed packages', 'Search and paginate managed and unlocked packages installed in the org.'],
      ['Cached org reads', 'Reuse read-only org data with visible freshness and explicit refresh controls.'],
    ],
  },
  {
    title: 'Metadata & retrieval',
    description: 'Discover, select, package, retrieve, and export Salesforce metadata.',
    icon: Box,
    route: 'metadata',
    routeLabel: 'Open metadata browser',
    items: [
      ['Metadata type discovery', 'Load the metadata types supported by the selected org.'],
      ['Lazy component browser', 'Load component API names only when a metadata type is expanded.'],
      ['Fuzzy metadata search', 'Rank approximate matches across metadata types and loaded components.'],
      ['Component and wildcard selection', 'Select individual members or include an entire metadata type.'],
      ['Curated selection presets', 'Quick-select common Apex, frontend, object, automation, and security metadata.'],
      ['Persistent selection basket', 'Keep the current metadata selection while moving between application workspaces.'],
      ['Saved selections', 'Create, reopen, and delete reusable metadata component sets stored on this device.'],
      ['package.xml generation', 'Create a sorted, escaped Salesforce manifest with an explicit API version.'],
      ['package.xml upload', 'Validate an existing local manifest and use it as retrieval input.'],
      ['Retrieve preview', 'Ask Salesforce CLI to preview source-tracking effects before retrieval.'],
      ['Asynchronous metadata retrieval', 'Start selected-component or uploaded-manifest retrieval jobs without blocking the interface.'],
      ['Retrieval history and errors', 'Track pending, completed, and failed jobs in persistent local history.'],
      ['ZIP download', 'Download completed retrieval output from the local workspace.'],
      ['Exact Flow version export', 'Search saved Flow versions and export a specific version as a downloadable ZIP.'],
    ],
  },
  {
    title: 'Data & schema',
    description: 'Explore schema, query records, and perform guarded record operations.',
    icon: Database,
    route: 'query',
    routeLabel: 'Open SOQL query',
    items: [
      ['Standard and custom object explorer', 'Browse searchable object catalogs from the active org.'],
      ['Object describe', 'Inspect field types, create/update access, and nullability.'],
      ['Multi-object record counts', 'Run aggregate counts for selected objects with bounded CLI concurrency.'],
      ['Record-count CSV export', 'Download object totals as a spreadsheet-ready CSV file.'],
      ['SOQL query editor', 'Execute Salesforce data queries through the fixed local CLI bridge.'],
      ['Tooling API mode', 'Opt in per query to work with Tooling API objects and records.'],
      ['Schema-aware completion', 'Suggest object and field API names using fuzzy matching.'],
      ['SELECT field expansion', 'Insert fields for the FROM object by pressing Tab after SELECT.'],
      ['Scalable query results', 'Review large result sets in a paginated, horizontally scrollable data table.'],
      ['Row selection and Excel copy', 'Copy all or selected rows as tab-separated values.'],
      ['Query CSV export', 'Download the current result set with correct CSV escaping.'],
      ['Guarded record deletion', 'Delete selected query records only after exact confirmation, with per-record outcomes.'],
      ['Record inspector', 'Load a single Salesforce or Tooling API record by object and ID.'],
      ['Schema-aware record editing', 'Edit updateable fields with typed controls and nearby Salesforce validation feedback.'],
    ],
  },
  {
    title: 'Source code editor',
    description: 'Retrieve and manage supported Salesforce source in an IDE-style workspace.',
    icon: FileCode2,
    route: 'editor',
    routeLabel: 'Open code editor',
    items: [
      ['Supported source catalog', 'Browse Apex classes, triggers, Visualforce pages/components, LWC, and Aura bundles.'],
      ['Managed component filtering', 'Exclude installed managed-package components from the editable source catalog.'],
      ['VS Code-style source tree', 'Expand a component to reveal every file in LWC and Aura bundles.'],
      ['Tabbed multi-file editing', 'Open several source files and switch between them without losing local edits.'],
      ['Syntax-aware editor', 'Use line numbers, selection highlighting, indentation, matching brackets, and language-aware coloring.'],
      ['Find and replace', 'Use a VS Code-style Ctrl+F panel with match options, navigation, replace, and replace-all.'],
      ['Editor view controls', 'Toggle word wrap, adjust font size, and enter a focused zen workspace.'],
      ['Create Salesforce source', 'Generate and deploy safe starter files for supported source and bundle types.'],
      ['Add bundle files', 'Add optional LWC styles and supported Aura controller, helper, renderer, style, design, docs, or SVG files.'],
      ['Retrieve and refresh source', 'Open from the local cache or explicitly re-retrieve the component from Salesforce.'],
      ['Save and deploy', 'Write the current file locally and deploy its component back to the selected org.'],
      ['Guarded rename', 'Create the renamed component, update supported declarations, and remove the old component after exact confirmation.'],
      ['Guarded delete', 'Generate a destructive deployment only after an exact component-specific confirmation.'],
      ['Fixed-height deployment logs', 'Review save/deploy output in a scrollable, manually resizable log panel that does not auto-grow.'],
    ],
  },
  {
    title: 'Apex & diagnostics',
    description: 'Execute Apex, run tests, inspect coverage, and investigate debug output.',
    icon: Code2,
    route: 'apex',
    routeLabel: 'Open Anonymous Apex',
    items: [
      ['Anonymous Apex execution', 'Execute an Apex script through sf apex run and review structured output.'],
      ['Configurable test runs', 'Run local, all-org, or specifically selected Apex tests.'],
      ['Code coverage results', 'Request and review coverage together with Salesforce test results.'],
      ['Debug log inventory', 'Search and paginate recent Salesforce execution logs.'],
      ['Full debug log viewer', 'Download, inspect, and copy complete log contents without leaving the application.'],
    ],
  },
  {
    title: 'Project deployment',
    description: 'Guarded deployment operations for an existing local Salesforce project.',
    icon: Rocket,
    route: 'deploy',
    routeLabel: 'Open deployment workbench',
    items: [
      ['Local project deployment preview', 'Inspect source changes before modifying the target org.'],
      ['Validation-only deployment', 'Run a check-only deployment with the selected Salesforce test level.'],
      ['Asynchronous deployment', 'Submit a protected source deployment and keep the interface responsive.'],
      ['Deployment reporting', 'Poll Salesforce result details for a submitted deployment job ID.'],
      ['Quick deploy', 'Deploy a previously successful validation by its Salesforce job ID.'],
      ['Deployment cancellation', 'Cancel an active deployment request through a fixed API operation.'],
      ['Live job tracking', 'Show running retrievals and deployments with current state and elapsed time.'],
      ['Destructive-operation guards', 'Require explicit target context and exact confirmation before high-impact actions.'],
    ],
  },
  {
    title: 'Org-to-org delivery',
    description: 'Compare selected source metadata and safely deliver a reviewed scope to another org.',
    icon: GitCompare,
    route: 'orgDeploy',
    routeLabel: 'Open org-to-org deploy',
    items: [
      ['Guided five-step workflow', 'Choose orgs, select metadata, compare, configure, and review execution results.'],
      ['Independent source and target orgs', 'Require two different connected Salesforce orgs before comparison.'],
      ['Source metadata selection', 'Browse and fuzzy-search live source metadata types and component API names.'],
      ['Normalized component comparison', 'Group flat files and multi-file bundles into deployable Salesforce components.'],
      ['Difference classification', 'Identify new, changed, identical, target-only, and unknown components.'],
      ['Side-by-side file diff', 'Inspect source and target text with per-line changes and multi-file bundle navigation.'],
      ['Comparison filters and CSV export', 'Filter by status, type, or name and export the reviewed results.'],
      ['Dependency scan', 'Flag referenced Apex classes that may be missing from the selection or target org.'],
      ['Automatic field-level security scope', 'Include source Profiles and Permission Sets when Custom Fields require their FLS.'],
      ['Explicit target deletions', 'Never delete target-only metadata automatically; selected deletions become destructiveChangesPost.xml.'],
      ['Scoped deployment preview', 'Review the exact package.xml, destructive changes, component count, and target before execution.'],
      ['Validation and deployment test settings', 'Choose validation or deployment with supported Salesforce test levels and specified tests.'],
      ['Persistent delivery history', 'Track the latest org-to-org validation and deployment records on this device.'],
    ],
  },
  {
    title: 'Desktop platform & safety',
    description: 'Local productivity infrastructure shared by every Salesforce workflow.',
    icon: ShieldCheck,
    route: 'overview',
    routeLabel: 'Open workspace overview',
    items: [
      ['Local Salesforce CLI bridge', 'Map supported UI operations to fixed sf command families without exposing a terminal.'],
      ['Credential isolation', 'Keep Salesforce authentication in the official CLI store; raw tokens and SFDX auth URLs never reach the browser.'],
      ['Loopback-only API', 'Serve the application API on 127.0.0.1 instead of exposing it to the network.'],
      ['Database-free persistence', 'Store preferences, saved selections, retrievals, and histories in local device files.'],
      ['Operation history', 'Review recent local API outcomes without retaining credentials or raw command arguments.'],
      ['Overlay navigation', 'Reach all workspaces through a searchable drawer that never resizes the active workspace.'],
      ['Command palette', 'Jump to pages, orgs, and common actions using Ctrl+K fuzzy search.'],
      ['Deep links and browser history', 'Preserve back, forward, refresh, and per-object URLs with hash routing.'],
      ['Dark and light themes', 'Follow the operating system initially and remember the selected appearance.'],
      ['Shared job and status surfaces', 'Keep current page, org, connection, refresh, and background-job context visible.'],
      ['Desktop application updates', 'Check, download, install, and restart from a GitHub Release when running in Electron.'],
      ['Accessible interaction states', 'Provide keyboard navigation, visible focus, semantic controls, loading states, errors, and non-blocking toasts.'],
    ],
  },
];

export const CAPABILITY_TOTAL = CAPABILITY_GROUPS.reduce((total, group) => total + group.items.length, 0);
