import { HighlightStyle } from '@codemirror/language';
import { EditorView } from '@codemirror/view';
import { tags as t } from '@lezer/highlight';

/** The editor consumes the centralized technical palette and intentionally remains dark. */
const palette = {
  background: 'var(--editor-bg)',
  lineHighlight: 'var(--editor-line)',
  gutterBackground: 'var(--editor-gutter)',
  gutterText: 'var(--editor-gutter-text)',
  foreground: 'var(--editor-foreground)',
  comment: 'var(--editor-comment)',
  keyword: 'var(--editor-keyword)',
  literal: 'var(--editor-literal)',
  type: 'var(--editor-type)',
  func: 'var(--editor-function)',
  selection: 'var(--editor-selection)',
  cursor: 'var(--editor-foreground)',
  accent: 'var(--accent-primary)',
};

export const editorTheme = EditorView.theme(
  {
    '&': { height: '100%', backgroundColor: palette.background, color: palette.foreground },
    '.cm-scroller': { fontFamily: 'var(--font-mono)', lineHeight: '1.6', overflow: 'auto' },
    '.cm-content': { padding: 'var(--s-3) 0', caretColor: palette.cursor },
    '.cm-cursor, .cm-dropCursor': { borderLeftColor: palette.cursor },
    '.cm-gutters': { backgroundColor: palette.gutterBackground, color: palette.gutterText, border: 'none' },
    '.cm-lineNumbers .cm-gutterElement': { color: palette.gutterText },
    '.cm-activeLine': { backgroundColor: palette.lineHighlight, boxShadow: `inset 3px 0 0 ${palette.accent}` },
    '.cm-activeLineGutter': { backgroundColor: palette.lineHighlight, color: palette.foreground },
    '&.cm-focused': { outline: 'none' },
    '.cm-selectionBackground, &.cm-focused .cm-selectionBackground, ::selection': {
      backgroundColor: `${palette.selection} !important`,
    },
    '.cm-matchingBracket, .cm-nonmatchingBracket': {
      backgroundColor: 'var(--accent-primary-soft)',
      outline: `1px solid ${palette.accent}`,
      color: 'inherit',
    },
    '.cm-tooltip': { backgroundColor: 'var(--code-bg-elevated)', border: '1px solid var(--code-border)', color: palette.foreground },
    '.cm-tooltip-autocomplete ul li[aria-selected]': { backgroundColor: palette.lineHighlight, color: palette.func },
    '.cm-panels': { backgroundColor: 'transparent', color: palette.foreground },
    '.cm-panels-top': {
      position: 'absolute',
      zIndex: '20',
      top: '7px',
      right: '15px',
      left: 'auto',
      border: 'none',
      pointerEvents: 'none',
    },
    '.cm-panel.cm-search.vscode-find-widget': {
      width: 'min(420px, calc(100vw - 310px))',
      minWidth: '390px',
      margin: '0',
      padding: '4px 5px',
      border: '1px solid var(--code-border)',
      borderRadius: '6px',
      backgroundColor: 'var(--code-bg-elevated)',
      boxShadow: 'var(--shadow-2)',
      color: 'var(--code-text)',
      fontFamily: 'var(--font-sans)',
      pointerEvents: 'auto',
      boxSizing: 'border-box',
    },
    '.vscode-find-row': {
      display: 'grid',
      gridTemplateColumns: '20px minmax(190px, 1fr) 68px repeat(4, 24px)',
      alignItems: 'center',
      gap: '2px',
      minHeight: '26px',
    },
    '.vscode-replace-row': { display: 'none', marginTop: '2px' },
    '.vscode-find-widget.is-replace-open .vscode-replace-row': { display: 'grid' },
    '.vscode-find-input': {
      display: 'flex',
      alignItems: 'center',
      minWidth: '0',
      height: '26px',
      border: '1px solid var(--code-border)',
      borderRadius: '2px',
      backgroundColor: 'var(--editor-bg)',
      boxSizing: 'border-box',
    },
    '.vscode-find-input:focus-within': { borderColor: 'var(--accent-primary)', boxShadow: 'inset 0 0 0 1px var(--accent-primary)' },
    '.vscode-find-textfield': {
      flex: '1',
      width: '100%',
      minWidth: '0',
      height: '24px',
      margin: '0',
      padding: '0 5px',
      border: '0',
      outline: '0',
      backgroundColor: 'transparent',
      color: 'var(--code-text)',
      fontFamily: 'var(--font-sans)',
      fontSize: '12px',
      boxSizing: 'border-box',
    },
    '.vscode-find-textfield::placeholder': { color: 'var(--editor-gutter-text)', opacity: '1' },
    '.vscode-find-options': { display: 'flex', alignItems: 'center', gap: '1px', paddingRight: '2px' },
    '.vscode-find-widget button': {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '24px',
      height: '24px',
      minWidth: '0',
      margin: '0',
      padding: '0',
      border: '1px solid transparent',
      borderRadius: '3px',
      outline: 'none',
      backgroundImage: 'none',
      backgroundColor: 'transparent',
      color: 'var(--text-muted)',
      fontFamily: 'var(--font-sans)',
      lineHeight: '1',
      cursor: 'pointer',
      boxSizing: 'border-box',
    },
    '.vscode-find-widget button:hover:not(:disabled)': { backgroundColor: 'var(--editor-line)', color: 'var(--editor-foreground)' },
    '.vscode-find-widget button:focus-visible': { outline: '1px solid var(--accent-primary)', outlineOffset: '-1px', color: 'var(--editor-foreground)' },
    '.vscode-find-widget button:disabled': { opacity: '.5', cursor: 'default' },
    '.vscode-find-icon svg': { width: '16px', height: '16px' },
    '.vscode-find-option': { width: '21px !important', height: '21px !important', color: 'var(--code-text) !important', fontSize: '11px' },
    '.vscode-find-option.is-word': { textDecoration: 'underline', textUnderlineOffset: '2px' },
    '.vscode-find-option[aria-pressed="true"]': { borderColor: 'var(--accent-primary)', backgroundColor: 'var(--accent-primary-soft)', color: 'var(--accent-primary-hover) !important' },
    '.vscode-find-widget button[name="close"]': { position: 'static', top: 'auto', right: 'auto' },
    '.vscode-replace-toggle': { width: '20px !important' },
    '.vscode-replace-toggle svg': { transition: 'transform 80ms ease' },
    '.vscode-replace-toggle[aria-expanded="true"] svg': { transform: 'rotate(90deg)' },
    '.vscode-find-count': {
      overflow: 'hidden',
      padding: '0 3px',
      color: 'var(--text-muted)',
      fontSize: '11px',
      lineHeight: '24px',
      textAlign: 'center',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
    '.vscode-replace-row .vscode-find-input': { gridColumn: '2' },
    '.vscode-replace-row button[name="replace"]': { gridColumn: '4' },
    '.vscode-replace-row button[name="replaceAll"]': { gridColumn: '5' },
    '.cm-searchMatch': { backgroundColor: 'var(--editor-search-match)', outline: '1px solid var(--status-warning-border)' },
    '.cm-searchMatch.cm-searchMatch-selected': { backgroundColor: 'var(--editor-search-selected)', outline: `1px solid ${palette.accent}` },
    '.cm-foldPlaceholder': { backgroundColor: 'transparent', border: 'none', color: palette.comment },
    '.cm-foldGutter span': { cursor: 'pointer', color: palette.gutterText },
  },
  { dark: true },
);

export const editorHighlightStyle = HighlightStyle.define([
  { tag: [t.comment, t.lineComment, t.blockComment], color: palette.comment, fontStyle: 'italic' },
  { tag: [t.string, t.special(t.string)], color: palette.literal, fontStyle: 'italic' },
  { tag: t.regexp, color: palette.literal },
  { tag: [t.number, t.bool, t.null], color: palette.literal, fontStyle: 'italic' },
  { tag: [t.keyword, t.controlKeyword, t.operatorKeyword], color: palette.keyword },
  { tag: [t.definitionKeyword, t.modifier], color: palette.keyword },
  { tag: [t.function(t.variableName), t.function(t.propertyName)], color: palette.func },
  { tag: t.propertyName, color: palette.literal, fontStyle: 'italic' },
  { tag: [t.typeName, t.className, t.namespace], color: palette.type },
  { tag: t.definition(t.variableName), color: palette.foreground },
  { tag: t.variableName, color: palette.foreground },
  { tag: [t.operator, t.punctuation], color: palette.foreground },
  { tag: [t.bracket, t.paren, t.squareBracket, t.brace, t.angleBracket], color: palette.foreground },
  { tag: t.tagName, color: palette.keyword },
  { tag: t.attributeName, color: palette.literal, fontStyle: 'italic' },
  { tag: t.attributeValue, color: palette.literal },
  { tag: [t.atom, t.self], color: palette.literal },
  { tag: t.meta, color: palette.comment },
  { tag: t.invalid, color: 'var(--editor-invalid)', textDecoration: 'underline' },
  { tag: t.link, color: palette.type, textDecoration: 'underline' },
  { tag: t.heading, color: palette.keyword, fontWeight: 'bold' },
]);
