import { HighlightStyle } from '@codemirror/language';
import { EditorView } from '@codemirror/view';
import { tags as t } from '@lezer/highlight';

/**
 * A dark IDE palette modeled on Lightning Studio's own editor theme: near-black background,
 * pink selectors/keywords, warm tan property names and literals, cyan italic comments. Colors
 * are literal hex, independent of the app's own light/dark toggle — the code editor always
 * renders in this theme, the way a dedicated code color scheme usually isn't tied to app chrome.
 */
const palette = {
  background: '#1e1e1e',
  lineHighlight: '#2a2d2e',
  gutterBackground: '#1e1e1e',
  gutterText: '#6a6a6a',
  foreground: '#d4d4d4',
  comment: '#7ec9e8',
  keyword: '#ff6ac1',
  tan: '#d19a66',
  type: '#4ec9b0',
  func: '#8fd19e',
  selection: '#264f78',
  cursor: '#d4d4d4',
  accent: '#4fc1e9',
};

export const editorTheme = EditorView.theme(
  {
    '&': { height: '100%', backgroundColor: palette.background, color: palette.foreground },
    '.cm-scroller': { fontFamily: 'var(--font-mono)', lineHeight: '1.6', overflow: 'auto' },
    '.cm-content': { padding: 'var(--s-3) 0', caretColor: palette.cursor },
    '.cm-cursor, .cm-dropCursor': { borderLeftColor: palette.cursor },
    '.cm-gutters': { backgroundColor: palette.gutterBackground, color: palette.gutterText, border: 'none' },
    '.cm-lineNumbers .cm-gutterElement': { color: palette.gutterText },
    '.cm-activeLine': { backgroundColor: palette.lineHighlight, boxShadow: `inset 3px 0 0 ${palette.accent}` },
    '.cm-activeLineGutter': { backgroundColor: palette.lineHighlight, color: palette.foreground },
    '&.cm-focused': { outline: 'none' },
    '.cm-selectionBackground, &.cm-focused .cm-selectionBackground, ::selection': {
      backgroundColor: `${palette.selection} !important`,
    },
    '.cm-matchingBracket, .cm-nonmatchingBracket': {
      backgroundColor: 'rgba(79, 193, 233, 0.18)',
      outline: `1px solid ${palette.accent}`,
      color: 'inherit',
    },
    '.cm-tooltip': { backgroundColor: '#252526', border: '1px solid #3c3c3c', color: palette.foreground },
    '.cm-tooltip-autocomplete ul li[aria-selected]': { backgroundColor: palette.lineHighlight, color: palette.func },
    '.cm-panels': { backgroundColor: 'transparent', color: palette.foreground },
    '.cm-panels-top': {
      position: 'absolute',
      zIndex: '20',
      top: '7px',
      right: '15px',
      left: 'auto',
      border: 'none',
      pointerEvents: 'none',
    },
    '.cm-panel.cm-search.vscode-find-widget': {
      width: 'min(420px, calc(100vw - 310px))',
      minWidth: '390px',
      margin: '0',
      padding: '4px 5px',
      border: '1px solid #3c3c3c',
      borderRadius: '6px',
      backgroundColor: '#252526',
      boxShadow: '0 4px 14px rgba(0, 0, 0, .44)',
      color: '#cccccc',
      fontFamily: 'var(--font-ui)',
      pointerEvents: 'auto',
      boxSizing: 'border-box',
    },
    '.vscode-find-row': {
      display: 'grid',
      gridTemplateColumns: '20px minmax(190px, 1fr) 68px repeat(4, 24px)',
      alignItems: 'center',
      gap: '2px',
      minHeight: '26px',
    },
    '.vscode-replace-row': { display: 'none', marginTop: '2px' },
    '.vscode-find-widget.is-replace-open .vscode-replace-row': { display: 'grid' },
    '.vscode-find-input': {
      display: 'flex',
      alignItems: 'center',
      minWidth: '0',
      height: '26px',
      border: '1px solid #3c3c3c',
      borderRadius: '2px',
      backgroundColor: '#1f1f1f',
      boxSizing: 'border-box',
    },
    '.vscode-find-input:focus-within': { borderColor: '#007acc', boxShadow: 'inset 0 0 0 1px #007acc' },
    '.vscode-find-textfield': {
      flex: '1',
      width: '100%',
      minWidth: '0',
      height: '24px',
      margin: '0',
      padding: '0 5px',
      border: '0',
      outline: '0',
      backgroundColor: 'transparent',
      color: '#cccccc',
      fontFamily: 'var(--font-ui)',
      fontSize: '12px',
      boxSizing: 'border-box',
    },
    '.vscode-find-textfield::placeholder': { color: '#7f7f7f', opacity: '1' },
    '.vscode-find-options': { display: 'flex', alignItems: 'center', gap: '1px', paddingRight: '2px' },
    '.vscode-find-widget button': {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '24px',
      height: '24px',
      minWidth: '0',
      margin: '0',
      padding: '0',
      border: '1px solid transparent',
      borderRadius: '3px',
      outline: 'none',
      backgroundImage: 'none',
      backgroundColor: 'transparent',
      color: '#9d9d9d',
      fontFamily: 'var(--font-ui)',
      lineHeight: '1',
      cursor: 'pointer',
      boxSizing: 'border-box',
    },
    '.vscode-find-widget button:hover:not(:disabled)': { backgroundColor: '#3a3d41', color: '#f0f0f0' },
    '.vscode-find-widget button:focus-visible': { outline: '1px solid #007acc', outlineOffset: '-1px', color: '#f0f0f0' },
    '.vscode-find-widget button:disabled': { opacity: '.5', cursor: 'default' },
    '.vscode-find-icon svg': { width: '16px', height: '16px' },
    '.vscode-find-option': { width: '21px !important', height: '21px !important', color: '#cccccc !important', fontSize: '11px' },
    '.vscode-find-option.is-word': { textDecoration: 'underline', textUnderlineOffset: '2px' },
    '.vscode-find-option[aria-pressed="true"]': { borderColor: '#007acc', backgroundColor: '#094771', color: '#ffffff !important' },
    '.vscode-find-widget button[name="close"]': { position: 'static', top: 'auto', right: 'auto' },
    '.vscode-replace-toggle': { width: '20px !important' },
    '.vscode-replace-toggle svg': { transition: 'transform 80ms ease' },
    '.vscode-replace-toggle[aria-expanded="true"] svg': { transform: 'rotate(90deg)' },
    '.vscode-find-count': {
      overflow: 'hidden',
      padding: '0 3px',
      color: '#b5b5b5',
      fontSize: '11px',
      lineHeight: '24px',
      textAlign: 'center',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
    '.vscode-replace-row .vscode-find-input': { gridColumn: '2' },
    '.vscode-replace-row button[name="replace"]': { gridColumn: '4' },
    '.vscode-replace-row button[name="replaceAll"]': { gridColumn: '5' },
    '.cm-searchMatch': { backgroundColor: 'rgba(209, 154, 102, 0.30)', outline: '1px solid rgba(209, 154, 102, 0.36)' },
    '.cm-searchMatch.cm-searchMatch-selected': { backgroundColor: 'rgba(79, 193, 233, 0.34)', outline: `1px solid ${palette.accent}` },
    '.cm-foldPlaceholder': { backgroundColor: 'transparent', border: 'none', color: palette.comment },
    '.cm-foldGutter span': { cursor: 'pointer', color: palette.gutterText },
  },
  { dark: true },
);

export const editorHighlightStyle = HighlightStyle.define([
  { tag: [t.comment, t.lineComment, t.blockComment], color: palette.comment, fontStyle: 'italic' },
  { tag: [t.string, t.special(t.string)], color: palette.tan, fontStyle: 'italic' },
  { tag: t.regexp, color: palette.tan },
  { tag: [t.number, t.bool, t.null], color: palette.tan, fontStyle: 'italic' },
  { tag: [t.keyword, t.controlKeyword, t.operatorKeyword], color: palette.keyword },
  { tag: [t.definitionKeyword, t.modifier], color: palette.keyword },
  { tag: [t.function(t.variableName), t.function(t.propertyName)], color: palette.func },
  { tag: t.propertyName, color: palette.tan, fontStyle: 'italic' },
  { tag: [t.typeName, t.className, t.namespace], color: palette.type },
  { tag: t.definition(t.variableName), color: palette.foreground },
  { tag: t.variableName, color: palette.foreground },
  { tag: [t.operator, t.punctuation], color: palette.foreground },
  { tag: [t.bracket, t.paren, t.squareBracket, t.brace, t.angleBracket], color: palette.foreground },
  { tag: t.tagName, color: palette.keyword },
  { tag: t.attributeName, color: palette.tan, fontStyle: 'italic' },
  { tag: t.attributeValue, color: palette.tan },
  { tag: [t.atom, t.self], color: palette.tan },
  { tag: t.meta, color: palette.comment },
  { tag: t.invalid, color: '#f14c4c', textDecoration: 'underline' },
  { tag: t.link, color: palette.type, textDecoration: 'underline' },
  { tag: t.heading, color: palette.keyword, fontWeight: 'bold' },
]);
